### PR TITLE
added install steps for convenience

### PR DESCRIPTION
**Pull request by thirschbuechler**
added install steps for convenience
maybe this could prevent potential user fustration with the installation

### CODE REVIEW

**Comment by maoschanz** [comment]
If this isn't on extensions.gnome.org, there is a reason.

**Comment by maoschanz** [comment]
Instructions will be clearer when the extension will work

**Comment by maoschanz** [comment]
Now the extension works (but i updated the readme myself: you don't have to compile translations, and you don't have to uninstall Ubuntu Dock)

**Comment by thirschbuechler** [comment]
nice, I'll have to give that a shot!

What do you mean "when it works"? Clearly it has basic functionality and could be expanded (i.e. file pinning, showing the list always (not in a dropdown menu) etc.

Do you refer to that or to the publishing as a fleshed-out extension?

Right now I aim to move to Ubuntu 18.04, remembered that I don't want to "live" in an OS without recent-files lists, tried installing it, forgot how to, and therefore made another attempt at updating the Readme^^

**Comment by maoschanz** [comment]
>Clearly it has basic functionality

Now it has, since yesterday. Before that, it didn't (it was crashing on GS 3.32, it was showing deleted/renamed/moved files, memory was ridiculously used, etc.)

>showing the list always (not in a dropdown menu)

This is an existing option.

>Do you refer to that or to the publishing as a fleshed-out extension?

No one is supposed to install extensions from github, there is no way to update them this way, people are supposed to install them from GNOME Software or from extensions.gnome.org: if an extension isn't there you should assume it's not ready to be used

**Comment by maoschanz** [comment]
FYI it is now here https://extensions.gnome.org/extension/1747/quicklists/

**Comment by thirschbuechler** [comment]
That's awesome, congrats to the launch! :)

> No one is supposed to install extensions from github

Well, our linux-expieriences wildly differ, then. Many times getting stuff directly from github is the only alternative to not getting it at all ;)

Further readme suggestions:
- Install from https://extensions.gnome.org/extension/1747/quicklists/ unless possibly out-of-date dev-version desired
- Boomkarks = File-explorer bookmarks, not selected files (no file pinning, yet..?)
- how to troubleshoot if opening a file from recent-menu does
-- nothing
-- file not existant error (should probably remove this entry and refresh, maybe from the OS recentmanager if necessary, or check on its own fileexists)

Cheers

**Comment by maoschanz** [comment]
Link added 👍

>file not existant error (should probably remove this entry and refresh, maybe from the OS recentmanager if necessary, or check on its own fileexists)

This shouldn't happen since it's what i fixed 13 days ago. In my opinion, people with issues should open issues, then troubleshooting can begin

**Pull request closed without merging**
